---
title: "Biodiversity in the park"
date: "11/19/2022"
linkTitle: "Biodiversity in the park"
author: "Rebecca Wilcox"
categories:
  - outreach
---

## Biodiversity in the park

<!-- add info here -->

Rebecca worked with California Academy of Sciences (CAS) Curator of Botany Sarah Jacobs to teach a course entitled "Biodiversity in the Park", for the [Careers in Science intern program at CAS](https://www.calacademy.org/careers-in-science-cis-intern-program). Careers in Science is an internship at CAS where high school students from communities traditionally underrepresented in STEM take courses and learn about careers in STEM. In Biodiversity in the park, students learned about biodiversity, wildlife communities, how to conduct biodiversity surveys, and how to analyze and interpret biodiversity data. To observe biodiversity up close, the class visited and surveyed plants and birds in three different ecosystems in Golden Gate Park: a redwood forest (the SF botanical garden), an oak woodland (Oak Woodlands Natural area in GGP), and a grassland (the living roof of CAS).

