---
date: "12/15/2021"
title: "December 2021"
linkTitle: "December 2021"
author: "Durrell Kapan"
---

# December 2021

<!-- add info here -->

## Working on Wildlife Resilience during a pandemic!

We had a busy year despite the mandatory social distancing! This year our interdisciplinary team met remotely over 20 times and build a draft a dynamic food web for Sierra Nevada forests from the TCSI study area. We started by compiling an all taxa species list (\>5800 entries) put together by USFS co-PIs Dr. Manley, Dr. White and Dr. Estes and used this to query online databases to compile biotic interactions between known species (over 2700 species). These interaction data were then filtered for predator-prey (tropic) interactions yielding over 12000 interactions with both predator and prey present on the landscape. These data were then curated by Dr. Jack Dumbacher and wildlife biologist from USFS PNW lab, Linda Long. Interactions are checked with guild and taxonomic information and then the food-webs are then analyzed for various properties and summarized for various key wildlife species (e.g. number of prey or predators, for an example see Table 1).

|                            |                    |                    |                         |
|----------------------------|--------------------|--------------------|-------------------------|
| **Scientific Name**        | **Common Name**    | **Number of prey** | **Number of predators** |
| *Haliaeetus leucocephalus* | Bald Eagle         | 104                | 1                       |
| *Accipiter cooperii*       | Cooper\'s Hawk     | 89                 | 4                       |
| *Aquila chrysaetos*        | Golden Eagle       | 80                 | 0                       |
| *Accipiter striatus*       | Sharp-shinned Hawk | 78                 | 1                       |
| *Bubo virginianus*         | Great-horned Owl   | 74                 | 4                       |
| *Buteo jamaicensis*        | Red-tailed Hawk    | 56                 | 3                       |
| *Falco peregrinus*         | Peregrine Falcon   | 53                 | 3                       |
| *Accipiter gentilis*       | Goshawk            | 50                 | 1                       |
| *Falco mexicanus*          | Prairie Falcon     | 42                 | 1                       |
| *Asio otus*                | Long-eared Owl     | 38                 | 5                       |

: Table 1. Example of number of prey and number of predators for birds with the most known number of prey queried from [Global Biotic Interactions Database](https://www.globalbioticinteractions.org/). Note that the bird with the largest number of prey on the landscape is also one of the most well studied (Bald Eagle). This species is rare and highly water dependent, so it may not interact strongly with other species across forests in the TCSI study area, but the CWHR database will allow us to determine which species occur in each habitat allowing us to calculate the impact of species on local food webs based on their occupancy.
