project:
  type: website
  output-dir: gh-pages

website:
  title: " "
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true


