---
title: "Wildlife Resilience"
csl: nature.csl
---

## Wildlife Resilience

One goal of conservation and management is to support the health and resilience of forested landscapes. Biodiversity is important for enhancing both. However, evaluating resilience alone or links between biodiversity, health and resilience is challenging. To address this challenge, we are developing metrics to quantify and evaluate wildlife community health and resilience.

::: callout-tip
## Definitions

**Resilience**: the ability of a community to maintain integrity/character after a disturbance.

**Biodiversity**: the variety of life, in all forms. This includes the variety of species, the interactions between these species, and other functions life performs in communities and ecosystems.

**Health**: communities that are supportive of a variety of ecological processes.
:::

[![Resilience in a complex system is illustrated by the green surface. As the system evolves, it\'s current 'state' is defined by a ball travelling to different positions along the surface. Deeper 'troughs' represent increased resilience. If a disturbance can push the system sufficiently far (e.g. push a ball out of a trough) then the system can move to a new state (follow the dashed arrow to the new trough on the right).](images/Roopnarine_Angielczyk_2016_Resilience_Image.png){fig-alt="Figure from Roopnarine and Angielczyk 2016." fig-align="center"}](https://www.researchgate.net/publication/309242056_The_Stability_of_Ecological_Communities_as_an_Agent_of_Evolutionary_Selection)

## Why Care About Resilience?

Over the last 10+ years, the increase in wildfire places much of Western forests at risk. In the face of climate-driven increases in fire conditions exacerbated by a long history of forest fuel buildup due to fire suppression, federal and state governments, industry, forest communities and NGOs are all working together to increase the pace and scale of the restoration of forest resilience. In California, both state and federal agencies are spending billions of dollars to manage forests for climate and fire resilience. But what does this resilience management mean for the conservation and enhancement of the state's wildlife?

## The link between resilience and biodiversity

The world's forests harbor the vast majority of terrestrial species[@thestat2020b], therefore they are an important source of biodiversity worldwide. Species provide critical ecosystem services, including clean water, pollination, seed dispersal, and pest and disease control. Importantly, biodiversity provides the raw material for ecosystems to respond to change, bounce back or completely regenerate after a major disturbance. Biodiversity is critical for ecosystem health. To learn more, see [Biodiversity](biodiversity.qmd). <!-- <iframe src="pdf/Metrics_Wildlife_Community_Resilience_Summary.pdf" width="100%" height="1000px"> -->
